# IMPORTS

In [1]:
import pandas as pd
# Set the maximum number of rows to display to None (no limit)
pd.options.display.max_rows = None

# Set the maximum number of columns to display to None (no limit)
pd.options.display.max_columns = None

# Now when you print a DataFrame, it will show all rows and columns

# FEBRUARY

In [2]:
file_path = 'C:\\Users\\tiftor\\Vships\\Office BU Review - Singapore and Chennai and Belships - Singapore and Chennai and Belships\\BU Risk Register - Singapore.xlsx'
sheet_name = 'February 2024'

columns_to_extract = ['Month', 'Division', 'SMO','BU','Risk Category','Standard Risks','Responsible Role','Gross Impact','Gross Likelihood','Gross Severity','Mitigations & Control Measures','Net Impact','Net Likelihood','Net Severity','Further Actions','Status Update for Extreme & High']


feb = pd.read_excel(file_path, sheet_name=sheet_name, usecols=columns_to_extract)
feb.head(1)

C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Month,Division,SMO,BU,Risk Category,Standard Risks,Responsible Role,Gross Impact,Gross Likelihood,Gross Severity,Mitigations & Control Measures,Net Impact,Net Likelihood,Net Severity,Further Actions,Status Update for Extreme & High
0,2024-02-01,- Select -,Singapore,V.Ships,Accounting & Reporting,"Failure to accurately budget, forecast and mon...",Sathesh,3 - Major: \n5 - 7.5% change in EBITDA OR 5 ...,3 - Possible: \n40< & ≤60% probability of oc...,HIGH,Make sure all unbudgetted expenses go below th...,3 - Major: \n5 - 7.5% change in EBITDA OR 5 ...,2 - Unlikely: \n20< & ≤40% probability of oc...,MEDIUM,Monthly review of OPEX performance by OD/MD,NaN

In [3]:
file_path = 'C:\\Users\\tiftor\\Vships\\Office BU Review - Singapore and Chennai and Belships - Singapore and Chennai and Belships\\BU Risk Register - Singapore.xlsx'
sheet_name = 'March 2024'

columns_to_extract = ['Month', 'Division', 'SMO','BU','Risk Category','Standard Risks','Responsible Role','Gross Impact','Gross Likelihood','Gross Severity','Mitigations & Control Measures','Net Impact','Net Likelihood','Net Severity','Further Actions','Status Update for Extreme & High']


mar = pd.read_excel(file_path, sheet_name=sheet_name, usecols=columns_to_extract)
mar.head(1)

C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Month,Division,SMO,BU,Risk Category,Standard Risks,Responsible Role,Gross Impact,Gross Likelihood,Gross Severity,Mitigations & Control Measures,Net Impact,Net Likelihood,Net Severity,Further Actions,Status Update for Extreme & High
0,2024-03-01,- Select -,Singapore,V.Ships,Accounting & Reporting,"Failure to accurately budget, forecast and mon...",Sathesh,3 - Major: \n5 - 7.5% change in EBITDA OR 5 ...,3 - Possible: \n40< & ≤60% probability of oc...,HIGH,Make sure all unbudgetted expenses go below th...,3 - Major: \n5 - 7.5% change in EBITDA OR 5 ...,2 - Unlikely: \n20< & ≤40% probability of oc...,MEDIUM,Monthly review of OPEX performance by OD/MD,NaN

In [4]:
file_path = 'C:\\Users\\tiftor\\Vships\\Office BU Review - Singapore and Chennai and Belships - Singapore and Chennai and Belships\\BU Risk Register - Singapore.xlsx'
sheet_name = 'April 2024'

columns_to_extract = ['Month', 'Division', 'SMO','BU','Risk Category','Standard Risks','Responsible Role','Gross Impact','Gross Likelihood','Gross Severity','Mitigations & Control Measures','Net Impact','Net Likelihood','Net Severity','Further Actions','Status Update for Extreme & High']


apr = pd.read_excel(file_path, sheet_name=sheet_name, usecols=columns_to_extract)
apr.head(1)

C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Month,Division,SMO,BU,Risk Category,Standard Risks,Responsible Role,Gross Impact,Gross Likelihood,Gross Severity,Mitigations & Control Measures,Net Impact,Net Likelihood,Net Severity,Further Actions,Status Update for Extreme & High
0,2024-04-01,- Select -,Singapore,V.Ships,Accounting & Reporting,"Failure to accurately budget, forecast and mon...",NaN,- Select -,- Select -,-,NaN,- Select -,- Select -,-,NaN,NaN

In [5]:
file_path = 'C:\\Users\\tiftor\\Vships\\Office BU Review - Singapore and Chennai and Belships - Singapore and Chennai and Belships\\BU Risk Register - Singapore.xlsx'
sheet_name = 'May 2024'

columns_to_extract = ['Month', 'Division', 'SMO','BU','Risk Category','Standard Risks','Responsible Role','Gross Impact','Gross Likelihood','Gross Severity','Mitigations & Control Measures','Net Impact','Net Likelihood','Net Severity','Further Actions','Status Update for Extreme & High']


may = pd.read_excel(file_path, sheet_name=sheet_name, usecols=columns_to_extract)
may.head(1)

C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Month,Division,SMO,BU,Risk Category,Standard Risks,Responsible Role,Gross Impact,Gross Likelihood,Gross Severity,Mitigations & Control Measures,Net Impact,Net Likelihood,Net Severity,Further Actions,Status Update for Extreme & High
0,2024-05-01,- Select -,Singapore,V.Ships,Accounting & Reporting,"Failure to accurately budget, forecast and mon...",NaN,- Select -,- Select -,-,NaN,- Select -,- Select -,-,NaN,NaN

In [6]:
file_path = 'C:\\Users\\tiftor\\Vships\\Office BU Review - Singapore and Chennai and Belships - Singapore and Chennai and Belships\\BU Risk Register - Singapore.xlsx'
sheet_name = 'June 2024'

columns_to_extract = ['Month', 'Division', 'SMO','BU','Risk Category','Standard Risks','Responsible Role','Gross Impact','Gross Likelihood','Gross Severity','Mitigations & Control Measures','Net Impact','Net Likelihood','Net Severity','Further Actions','Status Update for Extreme & High']


jun = pd.read_excel(file_path, sheet_name=sheet_name, usecols=columns_to_extract)
jun.head(1)

C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Month,Division,SMO,BU,Risk Category,Standard Risks,Responsible Role,Gross Impact,Gross Likelihood,Gross Severity,Mitigations & Control Measures,Net Impact,Net Likelihood,Net Severity,Further Actions,Status Update for Extreme & High
0,2024-06-01,- Select -,Singapore,V.Ships,Accounting & Reporting,"Failure to accurately budget, forecast and mon...",NaN,- Select -,- Select -,-,NaN,- Select -,- Select -,-,NaN,NaN

In [7]:
file_path = 'C:\\Users\\tiftor\\Vships\\Office BU Review - Singapore and Chennai and Belships - Singapore and Chennai and Belships\\BU Risk Register - Singapore.xlsx'
sheet_name = 'July 2024'

columns_to_extract = ['Month', 'Division', 'SMO','BU','Risk Category','Standard Risks','Responsible Role','Gross Impact','Gross Likelihood','Gross Severity','Mitigations & Control Measures','Net Impact','Net Likelihood','Net Severity','Further Actions','Status Update for Extreme & High']


jul = pd.read_excel(file_path, sheet_name=sheet_name, usecols=columns_to_extract)
jul.head(1)

C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Month,Division,SMO,BU,Risk Category,Standard Risks,Responsible Role,Gross Impact,Gross Likelihood,Gross Severity,Mitigations & Control Measures,Net Impact,Net Likelihood,Net Severity,Further Actions,Status Update for Extreme & High
0,2024-07-01,- Select -,Singapore,V.Ships,Accounting & Reporting,"Failure to accurately budget, forecast and mon...",NaN,- Select -,- Select -,-,NaN,- Select -,- Select -,-,NaN,NaN

In [8]:
file_path = 'C:\\Users\\tiftor\\Vships\\Office BU Review - Singapore and Chennai and Belships - Singapore and Chennai and Belships\\BU Risk Register - Singapore.xlsx'
sheet_name = 'August 2024'

columns_to_extract = ['Month', 'Division', 'SMO','BU','Risk Category','Standard Risks','Responsible Role','Gross Impact','Gross Likelihood','Gross Severity','Mitigations & Control Measures','Net Impact','Net Likelihood','Net Severity','Further Actions','Status Update for Extreme & High']


aug = pd.read_excel(file_path, sheet_name=sheet_name, usecols=columns_to_extract)
aug.head(1)

C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Month,Division,SMO,BU,Risk Category,Standard Risks,Responsible Role,Gross Impact,Gross Likelihood,Gross Severity,Mitigations & Control Measures,Net Impact,Net Likelihood,Net Severity,Further Actions,Status Update for Extreme & High
0,2024-08-01,- Select -,Singapore,V.Ships,Accounting & Reporting,"Failure to accurately budget, forecast and mon...",NaN,- Select -,- Select -,-,Financial,- Select -,- Select -,-,NaN,NaN

In [9]:
file_path = 'C:\\Users\\tiftor\\Vships\\Office BU Review - Singapore and Chennai and Belships - Singapore and Chennai and Belships\\BU Risk Register - Singapore.xlsx'
sheet_name = 'September 2024'

columns_to_extract = ['Month', 'Division', 'SMO','BU','Risk Category','Standard Risks','Responsible Role','Gross Impact','Gross Likelihood','Gross Severity','Mitigations & Control Measures','Net Impact','Net Likelihood','Net Severity','Further Actions','Status Update for Extreme & High']


sep = pd.read_excel(file_path, sheet_name=sheet_name, usecols=columns_to_extract)
sep.head(1)

C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Month,Division,SMO,BU,Risk Category,Standard Risks,Responsible Role,Gross Impact,Gross Likelihood,Gross Severity,Mitigations & Control Measures,Net Impact,Net Likelihood,Net Severity,Further Actions,Status Update for Extreme & High
0,2024-09-01,- Select -,Singapore,V.Ships,Accounting & Reporting,"Failure to accurately budget, forecast and mon...",NaN,- Select -,- Select -,-,NaN,- Select -,- Select -,-,NaN,NaN

In [10]:
file_path = 'C:\\Users\\tiftor\\Vships\\Office BU Review - Singapore and Chennai and Belships - Singapore and Chennai and Belships\\BU Risk Register - Singapore.xlsx'
sheet_name = 'October 2024'

columns_to_extract = ['Month', 'Division', 'SMO','BU','Risk Category','Standard Risks','Responsible Role','Gross Impact','Gross Likelihood','Gross Severity','Mitigations & Control Measures','Net Impact','Net Likelihood','Net Severity','Further Actions','Status Update for Extreme & High']


oct = pd.read_excel(file_path, sheet_name=sheet_name, usecols=columns_to_extract)
oct.head(1)

C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Month,Division,SMO,BU,Risk Category,Standard Risks,Responsible Role,Gross Impact,Gross Likelihood,Gross Severity,Mitigations & Control Measures,Net Impact,Net Likelihood,Net Severity,Further Actions,Status Update for Extreme & High
0,2024-10-01,- Select -,Singapore,V.Ships,Accounting & Reporting,"Failure to accurately budget, forecast and mon...",Jaslyn,1 - Minor: \nEBITDA change of ≤2.5% OR Total...,1- Rare: \n≤20% probability of occurring wit...,LOW,NaN,1 - Minor: \nEBITDA change of ≤2.5% OR Total...,1- Rare: \n≤20% probability of occurring wit...,LOW,NaN,NaN

In [11]:
file_path = 'C:\\Users\\tiftor\\Vships\\Office BU Review - Singapore and Chennai and Belships - Singapore and Chennai and Belships\\BU Risk Register - Singapore.xlsx'
sheet_name = 'November 2024'

columns_to_extract = ['Month', 'Division', 'SMO','BU','Risk Category','Standard Risks','Responsible Role','Gross Impact','Gross Likelihood','Gross Severity','Mitigations & Control Measures','Net Impact','Net Likelihood','Net Severity','Further Actions','Status Update for Extreme & High']


nov = pd.read_excel(file_path, sheet_name=sheet_name, usecols=columns_to_extract)
nov.head(1)

C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Month,Division,SMO,BU,Risk Category,Standard Risks,Responsible Role,Gross Impact,Gross Likelihood,Gross Severity,Mitigations & Control Measures,Net Impact,Net Likelihood,Net Severity,Further Actions,Status Update for Extreme & High
0,2024-11-01,- Select -,Singapore,V.Ships,Accounting & Reporting,"Failure to accurately budget, forecast and mon...",Sathesh,- Select -,- Select -,-,NaN,- Select -,- Select -,-,NaN,NaN

In [12]:
file_path = 'C:\\Users\\tiftor\\Vships\\Office BU Review - Singapore and Chennai and Belships - Singapore and Chennai and Belships\\BU Risk Register - Singapore.xlsx'
sheet_name = 'December 2024'

columns_to_extract = ['Month', 'Division', 'SMO','BU','Risk Category','Standard Risks','Responsible Role','Gross Impact','Gross Likelihood','Gross Severity','Mitigations & Control Measures','Net Impact','Net Likelihood','Net Severity','Further Actions','Status Update for Extreme & High']


dec = pd.read_excel(file_path, sheet_name=sheet_name, usecols=columns_to_extract)
dec.head(1)

C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Month,Division,SMO,BU,Risk Category,Standard Risks,Responsible Role,Gross Impact,Gross Likelihood,Gross Severity,Mitigations & Control Measures,Net Impact,Net Likelihood,Net Severity,Further Actions,Status Update for Extreme & High
0,2024-12-01,- Select -,Singapore,V.Ships,Accounting & Reporting,"Failure to accurately budget, forecast and mon...",Sathesh,- Select -,- Select -,-,NaN,- Select -,- Select -,-,NaN,NaN

In [13]:
file_path = 'C:\\Users\\tiftor\\Vships\\Office BU Review - Singapore and Chennai and Belships - Singapore and Chennai and Belships\\BU Risk Register - Singapore.xlsx'
sheet_name = 'January 2025'

columns_to_extract = ['Month', 'Division', 'SMO','BU','Risk Category','Standard Risks','Responsible Role','Gross Impact','Gross Likelihood','Gross Severity','Mitigations & Control Measures','Net Impact','Net Likelihood','Net Severity','Further Actions','Status Update for Extreme & High']


jan2 = pd.read_excel(file_path, sheet_name=sheet_name, usecols=columns_to_extract)
jan2.head(1)

C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Month,Division,SMO,BU,Risk Category,Standard Risks,Responsible Role,Gross Impact,Gross Likelihood,Gross Severity,Mitigations & Control Measures,Net Impact,Net Likelihood,Net Severity,Further Actions,Status Update for Extreme & High
0,2025-01-01,Cargo,Singapore,V.Ships,Accounting & Reporting,"Failure to accurately budget, forecast and mon...",Jaslyn,3 - Major: \n5 - 7.5% change in EBITDA OR 5 ...,1- Rare: \n≤20% probability of occurring wit...,LOW,Monthly Financial result is valdiated by Head ...,2 - Moderate: \n2.5 - 5% change in EBITDA OR...,1- Rare: \n≤20% probability of occurring wit...,LOW,NaN,NaN

In [14]:
file_path = 'C:\\Users\\tiftor\\Vships\\Office BU Review - Singapore and Chennai and Belships - Singapore and Chennai and Belships\\BU Risk Register - Singapore.xlsx'
sheet_name = 'February 2025'

columns_to_extract = ['Month', 'Division', 'SMO','BU','Risk Category','Standard Risks','Responsible Role','Gross Impact','Gross Likelihood','Gross Severity','Mitigations & Control Measures','Net Impact','Net Likelihood','Net Severity','Further Actions','Status Update for Extreme & High']


feb2 = pd.read_excel(file_path, sheet_name=sheet_name, usecols=columns_to_extract)
feb2.head(1)

C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Month,Division,SMO,BU,Risk Category,Standard Risks,Responsible Role,Gross Impact,Gross Likelihood,Gross Severity,Mitigations & Control Measures,Net Impact,Net Likelihood,Net Severity,Further Actions,Status Update for Extreme & High
0,2025-02-01,- Select -,Singapore,V.Ships,Accounting & Reporting,"Failure to accurately budget, forecast and mon...",Sathesh,- Select -,- Select -,-,NaN,- Select -,- Select -,-,NaN,NaN

In [15]:
file_path = 'C:\\Users\\tiftor\\Vships\\Office BU Review - Singapore and Chennai and Belships - Singapore and Chennai and Belships\\BU Risk Register - Singapore.xlsx'
sheet_name = 'March 2025'

columns_to_extract = ['Month', 'Division', 'SMO','BU','Risk Category','Standard Risks','Responsible Role','Gross Impact','Gross Likelihood','Gross Severity','Mitigations & Control Measures','Net Impact','Net Likelihood','Net Severity','Further Actions','Status Update for Extreme & High']


mar2 = pd.read_excel(file_path, sheet_name=sheet_name, usecols=columns_to_extract)
mar2.head(1)

C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Month,Division,SMO,BU,Risk Category,Standard Risks,Responsible Role,Gross Impact,Gross Likelihood,Gross Severity,Mitigations & Control Measures,Net Impact,Net Likelihood,Net Severity,Further Actions,Status Update for Extreme & High
0,2025-03-01,- Select -,Singapore,V.Ships,Accounting & Reporting,"Failure to accurately budget, forecast and mon...",Jaslyn,2 - Moderate: \n2.5 - 5% change in EBITDA OR...,2 - Unlikely: \n20< & ≤40% probability of oc...,MEDIUM,"Budget, Forecast and Actual Financial results ...",1 - Minor: \nEBITDA change of ≤2.5% OR Total...,1- Rare: \n≤20% probability of occurring wit...,LOW,NaN,NaN

In [16]:
file_path = 'C:\\Users\\tiftor\\Vships\\Office BU Review - Singapore and Chennai and Belships - Singapore and Chennai and Belships\\BU Risk Register - Singapore.xlsx'
sheet_name = 'April 2025'

columns_to_extract = ['Month', 'Division', 'SMO','BU','Risk Category','Standard Risks','Responsible Role','Gross Impact','Gross Likelihood','Gross Severity','Mitigations & Control Measures','Net Impact','Net Likelihood','Net Severity','Further Actions','Status Update for Extreme & High']


apr2 = pd.read_excel(file_path, sheet_name=sheet_name, usecols=columns_to_extract)
apr2.head(1)

C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Month,Division,SMO,BU,Risk Category,Standard Risks,Responsible Role,Gross Impact,Gross Likelihood,Gross Severity,Mitigations & Control Measures,Net Impact,Net Likelihood,Net Severity,Further Actions,Status Update for Extreme & High
0,2025-04-01,- Select -,Singapore,V.Ships,Accounting & Reporting,"Failure to accurately budget, forecast and mon...",Financial,1 - Minor: \nEBITDA change of ≤2.5% OR Total...,1- Rare: \n≤20% probability of occurring wit...,LOW,"Budget, Forecast and Actual Financial results ...",1 - Minor: \nEBITDA change of ≤2.5% OR Total...,1- Rare: \n≤20% probability of occurring wit...,LOW,NaN,NaN

In [17]:
file_path = 'C:\\Users\\tiftor\\Vships\\Office BU Review - Singapore and Chennai and Belships - Singapore and Chennai and Belships\\BU Risk Register - Singapore.xlsx'
sheet_name = 'May 2025'

columns_to_extract = ['Month', 'Division', 'SMO','BU','Risk Category','Standard Risks','Responsible Role','Gross Impact','Gross Likelihood','Gross Severity','Mitigations & Control Measures','Net Impact','Net Likelihood','Net Severity','Further Actions','Status Update for Extreme & High']


may2 = pd.read_excel(file_path, sheet_name=sheet_name, usecols=columns_to_extract)
may2.head(1)

C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Month,Division,SMO,BU,Risk Category,Standard Risks,Responsible Role,Gross Impact,Gross Likelihood,Gross Severity,Mitigations & Control Measures,Net Impact,Net Likelihood,Net Severity,Further Actions,Status Update for Extreme & High
0,2025-05-01,- Select -,Singapore,V.Ships,Accounting & Reporting,"Failure to accurately budget, forecast and mon...",Jaslyn,2 - Moderate: \n2.5 - 5% change in EBITDA OR...,1- Rare: \n≤20% probability of occurring wit...,LOW,Financial results reviewed by Head of Financia...,2 - Moderate: \n2.5 - 5% change in EBITDA OR...,1- Rare: \n≤20% probability of occurring wit...,LOW,NaN,NaN

# ADD MONTH

# ADD MONTHS ON LIST

In [18]:
months = [feb, mar, apr, may, jun, jul, aug, sep, oct, nov, dec, jan2, feb2, mar2, apr2, may2]

# Concatenate the dataframes
concat_months = pd.concat(months, ignore_index=True)
concat_months.head(5)

,Month,Division,SMO,BU,Risk Category,Standard Risks,Responsible Role,Gross Impact,Gross Likelihood,Gross Severity,Mitigations & Control Measures,Net Impact,Net Likelihood,Net Severity,Further Actions,Status Update for Extreme & High
0,2024-02-01,- Select -,Singapore,V.Ships,Accounting & Reporting,"Failure to accurately budget, forecast and mon...",Sathesh,3 - Major: \n5 - 7.5% change in EBITDA OR 5 ...,3 - Possible: \n40< & ≤60% probability of oc...,HIGH,Make sure all unbudgetted expenses go below th...,3 - Major: \n5 - 7.5% change in EBITDA OR 5 ...,2 - Unlikely: \n20< & ≤40% probability of oc...,MEDIUM,Monthly review of OPEX performance by OD/MD,NaN
1,2024-02-01,- Select -,Singapore,V.Ships,Accounting & Reporting,Failure to accurately invoice customers for pr...,Sathesh,2 - Moderate: \n2.5 - 5% change in EBITDA OR...,2 - Unlikely: \n20< & ≤40% probability of oc...,MEDIUM,NaN,2 - Moderate: \n2.5 - 5% change in EBITDA OR...,2 - Unlikely: \n20< & ≤40% probability of oc...,MEDIUM,New AI tool now in SS to extract billing for O...,NaN
2,2024-02-01,- Select -,Singapore,V.Ships,Accounting & Reporting,Customers' failure/delays to remit finances ha...,Sathesh,4 - Severe: \n7.5 - 10% change in EBITDA OR ...,2 - Unlikely: \n20< & ≤40% probability of oc...,HIGH,Follow up on 10 days later after bill is submi...,4 - Severe: \n7.5 - 10% change in EBITDA OR ...,2 - Unlikely: \n20< & ≤40% probability of oc...,HIGH,Speficic dedicated meeting with top executives...,NaN
3,2024-02-01,- Select -,Singapore,V.Ships,Accounting & Reporting,Customers' failure/delays to remit finances ha...,Sathesh,4 - Severe: \n7.5 - 10% change in EBITDA OR ...,1- Rare: \n≤20% probability of occurring wit...,MEDIUM,Reminders will be sent to Client and inform CM...,4 - Severe: \n7.5 - 10% change in EBITDA OR ...,1- Rare: \n≤20% probability of occurring wit...,MEDIUM,"Specific focus on Barbarossa, Meghna",NaN
4,2024-02-01,- Select -,Singapore,V.Ships,Accounting & Reporting,Customers' failure/delays to remit finances ha...,Sathesh,4 - Severe: \n7.5 - 10% change in EBITDA OR ...,2 - Unlikely: \n20< & ≤40% probability of oc...,HIGH,Reminders to client sent every alternate day t...,4 - Severe: \n7.5 - 10% change in EBITDA OR ...,2 - Unlikely: \n20< & ≤40% probability of oc...,HIGH,Speficic dedicated meeting with top executives...,NaN

In [19]:
concat_months.tail(5)

,Month,Division,SMO,BU,Risk Category,Standard Risks,Responsible Role,Gross Impact,Gross Likelihood,Gross Severity,Mitigations & Control Measures,Net Impact,Net Likelihood,Net Severity,Further Actions,Status Update for Extreme & High
1003,2025-05-01,- Select -,Singapore,V.Ships,Security & Organised Crime,CORE+ Terrorism Risk,Group HSSEQ,- Select -,- Select -,-,NaN,1 - Minor: \nMinor illness or injury with no...,1- Rare: \n≤20% probability of occurring wit...,LOW,NaN,NaN
1004,2025-05-01,- Select -,Singapore,V.Ships,Security & Organised Crime,CORE+ Crime Risk,Group HSSEQ,- Select -,- Select -,-,NaN,1 - Minor: \nMinor illness or injury with no...,1- Rare: \n≤20% probability of occurring wit...,LOW,NaN,NaN
1005,2025-05-01,- Select -,Singapore,V.Ships,Security & Organised Crime,CORE+ War Risk,Group HSSEQ,- Select -,- Select -,-,NaN,1 - Minor: \nMinor illness or injury with no...,1- Rare: \n≤20% probability of occurring wit...,LOW,NaN,NaN
1006,2025-05-01,- Select -,Singapore,V.Ships,Security & Organised Crime,CORE+ Civil Unrest Risk,Group HSSEQ,- Select -,- Select -,-,NaN,1 - Minor: \nMinor illness or injury with no...,1- Rare: \n≤20% probability of occurring wit...,LOW,NaN,NaN
1007,2025-05-01,- Select -,Singapore,V.Ships,Security & Organised Crime,CORE+ Kidnap Risk,Group HSSEQ,- Select -,- Select -,-,NaN,1 - Minor: \nMinor illness or injury with no...,1- Rare: \n≤20% probability of occurring wit...,LOW,NaN,NaN

In [20]:
import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import Font, Alignment
import timeit

rS = timeit.default_timer()

file_path = 'C:\\Users\\tiftor\\Vships\\Operational Excellence - BPM (1)\\Executive Reports\\BU Risks\\BU Risk Register.xlsx'
sheet_name = 'Singapore'  # Name of the new sheet

try:
    # Load the existing workbook
    book = load_workbook(file_path)
    
    # Check if the sheet_name already exists, and if so, remove it
    if sheet_name in book.sheetnames:
        del book[sheet_name]
    
    # Save the workbook to apply the changes
    book.save(file_path)

    # Create a Pandas Excel writer using openpyxl as the engine
    with pd.ExcelWriter(file_path, engine='openpyxl') as writer:
        # Assign the existing workbook to the writer
        writer.book = book
        
        # Copy existing sheets to the writer
        writer.sheets = dict((ws.title, ws) for ws in book.worksheets)
        
        # Assuming 'concat_months' is your DataFrame that you want to write to the new sheet
        concat_months.to_excel(writer, sheet_name=sheet_name, index=False)

    # After saving through pandas, reload the workbook to modify properties
    book = load_workbook(file_path)
    sheet = book[sheet_name]

    # Set column width
    for col in sheet.columns:
        sheet.column_dimensions[col[0].column_letter].width = 20

    # Apply font, alignment, and text wrap to all cells
    for row in sheet.iter_rows():
        for cell in row:
            cell.font = Font(name="Amina", size=8)  # Adjust the font name as necessary
            # Here we add wrapText=True to ensure text wrapping
            cell.alignment = Alignment(horizontal="center", vertical="center", wrapText=True)

    # Save the changes to the workbook
    book.save(file_path)

except Exception as e:
    print(f"An error occurred: {e}")
    
rE = timeit.default_timer()
print ('Time: ', rE - rS)

Time:  21.906113499999996